app4/urls.py
from django.contrib import admin
from django.urls import path

from app4.views import indexView, postAnn, checkTitle, by_rubric, AnnDeleteView, AnnUpdateView

urlpatterns = [
    path('Friend/<int:pk>/update/', AnnUpdateView.as_view(), name='update'),
    path('Friend/<int:pk>/delete/', AnnDeleteView.as_view(), name='delete'),
    path('', indexView, name="index"),
    path('post/ajax/friend', postAnn, name="post_friend"),
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('get/ajax/validate/nickname', checkTitle, name="validate_nickname")
]

lab4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app4/', include('app4.urls')),
    path('admin/', admin.site.urls),
]

app4/models.py
from django.db import models

# Create your models here.


class Announcement(models.Model):

    # NICK NAME should be unique
    nick_name = models.CharField(max_length=100, verbose_name='Объявление',  unique =  True)
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(null=True, blank=True, verbose_name='Цена')
    rubric = models.ForeignKey('Rubric', on_delete=models.PROTECT, verbose_name=' Рубрика', null=True)

    def __str__(self):
        return self.nick_name


class Rubric (models .Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']

app4/forms.py
from .models import Announcement
from django import forms
import datetime


class AnnForm (forms.ModelForm):

    class Meta:
        model = Announcement
        fields = ('nick_name', 'description', 'price', 'rubric')

app4/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView

from .forms import AnnForm
from .models import Announcement, Rubric


def indexView(request):
    context = {}
    form = AnnForm(request.POST or None)
    friends = Announcement.objects.all()
    rubrics = Rubric.objects.all()
    context['form'] = form
    context['friends'] = friends
    context['rubrics'] = rubrics
    if request.POST:
        if form.is_valid():
            temp = form.cleaned_data.get("category")
            print(temp)
    # form = FriendForm()
    # friends = Friend.objects.all()
    return render(request, "app4/index.html", context)


def postAnn(request):
    if request.is_ajax and request.method == "POST":
        form = AnnForm(request.POST)
        if form.is_valid():
            instance = form.save()
            ser_instance = serializers.serialize('json', [instance, ])
            response_dict = {"instance": ser_instance, "rubric_name": str(form.cleaned_data["rubric"])}
            return JsonResponse(response_dict, status=200)
        else:
            return JsonResponse({"error": form.errors}, status=400)
    return JsonResponse({"error": ""}, status=400)


def checkTitle(request):
    if request.is_ajax and request.method == "GET":
        nick_name = request.GET.get("nick_name", None)
        if Announcement.objects.filter(nick_name = nick_name).exists():
            return JsonResponse({"valid":False}, status=200)
        else:
            return JsonResponse({"valid":True}, status=200)

    return JsonResponse({}, status=400)


def by_rubric(request, rubric_id):
    friends = Announcement.objects.filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    current_rubric = Rubric.objects.get(pk=rubric_id)
    context = {'friends': friends, 'rubrics': rubrics, 'current_rubric': current_rubric}
    return render(request, 'app4/by_rubric.html ', context)


class AnnDeleteView(DeleteView):
    template_name = 'app4/delete.html'
    model = Announcement
    success_url = reverse_lazy('index')


class AnnUpdateView(UpdateView):
    template_name = 'app4/update.html'
    success_url = reverse_lazy('index')
    model = Announcement
    fields = ('nick_name', 'description', 'price', 'rubric')
    template_name_suffix = '_update_form'

app4/templates/app4/by_rubric.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}{{ current_rubric.name }}{% endblock %}
{% block content %}
<style>
body {
background-color: #c0c0c0
}
</style>
<div class="container-fluid">
    <div class="row">ᅠ
    </div>
    <div class="row">
        <div class="form-group col">
            <h2 class="btn btn-lg btn-success">Рубрика: {{ current_rubric.name }}</h2>
            {% for friend in friends %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <img class="card-img-top" src="{% static 'app4/home2.jpg' %}" alt="1">
                    <h5 class="card-title">{{ friend.nick_name }}</h5>
                    <p class="card-text">{{ friend.description }}</p>
                    <p class="card-text"><p>{{ friend.price }}</p></p>
                    <a class="btn btn-primary">Купить</a>
                </div>
            </div>
{% endfor %}
        </div>
    </div>
{% endblock %}
</div>

app4/templates/app4/delete.html
{% extends "layout/base.html" %}

{% block title %}Delete Friend{% endblock %}

{% block content %}
<style>
body {
background-color: #c0c0c0
}
</style>
<section>
    <form action="" method="post">{% csrf_token %}
        <p>Вы действительно хотите удалить это объявление?</p>
        <input type="submit" value="Confirm" />
    </form>
    <a href="{% url 'index' %}"><button> decline </button></a>
</section>
{% endblock %}

app4/templates/app4/index.html
{% extends "layout/base.html" %}
{% load static %}
{% block content %}
<style>
body {
background-color: #c0c0c0
}
</style>
<div class="container">
    <div class="row">
        <div class="col ">
            ᅠ ᅠ
        </div>
    </div>
</div>
<div class="container-fluid">
    <form id="friend-form ">
        <div class="row ">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group col-2.5 ">
                <label class="col-5 badge-success" >{{ field.label }}</label>
                <label>{{ field }}</label>

            </div>
            {% endfor %}
            <input type="submit" class="btn btn-success btn-lg btn-block" value="Создать объявление" />
        </div>
    </form>
</div>
<hr />

<div class="container-fluid bg-white">
    <table class="table table-striped table-sm table-hover " id="my_friends">
        <thead class="thead-light">
            <tr>
                <th>Заголовок</th>
                <th>Описание</th>
                <th>Цена</th>
                <th>Рубрика</th>
                <th>Удалить</th>
                <th>Редактировать</th>
            </tr>
        </thead>
        <tbody>
        {% for friend in friends %}
        <tr>
            <td>{{friend.nick_name}}</td>
            <td>{{friend.description}}</td>
            <td>{{friend.price}}</td>
            <td>{{friend.rubric}}</td>
            <td><a  href="{% url 'delete' friend.pk %}"><img src="{% static 'app4/trash2.png' %}" alt="My image"></a></td>
            <td><a  href="{% url 'update' friend.pk %}"><img src="{% static 'app4/edit.png' %}" alt="My image1"></a></td>
            <td>{{friend.form.as_p}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}

{% block javascript %}
<script>
    /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
    */
    $("#friend-form").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();
        // make POST ajax call
        $.ajax({
            type: 'POST',
            url: "{% url 'post_friend' %}",
            data: serializedData,
            success: function (response) {
                // on successfull creating object
                // 1. clear the form.
                $("#friend-form").trigger('reset');
                // 2. focus to nickname input
                $("#id_nick_name").focus();

                // display the newly friend to table.
                var instance = JSON.parse(response["instance"]);
                var fields = instance[0]["fields"];
                var rubric_name = response["rubric_name"];
                $("#my_friends tbody").prepend(
                    `<tr>
                    <td>${fields["nick_name"]||""}</td>
                    <td>${fields["description"]||""}</td>
                    <td>${fields["price"]||""}</td>
                    <td>${rubric_name||""}</td>
                    <td><img src="{% static 'app4/trash2.png' %}" alt="My image"></td>
                    <td><img src="{% static 'app4/edit.png' %}" alt="My image1"></td>
                    </tr>`
                )
            },
            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        })
    })

    /*
    On focus out on input nickname,
    call AJAX get request to check if the nickName
    already exists or not.
    */
    $("#id_nick_name").focusout(function (e) {
        e.preventDefault();
        // get the nickname
        var nick_name = $(this).val();
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: "{% url 'validate_nickname' %}",
            data: {"nick_name": nick_name},
            success: function (response) {
                // if not valid user, alert the user
                if(!response["valid"]){
                    alert("Вы не можете создать объявление с тем же названием");
                    var nickName = $("#id_nick_name");
                    nickName.val("")
                    nickName.focus()
                }
            },
            error: function (response) {
                console.log(response)
            }
        })
    })
</script>
{% endblock javascript %}

app4/templates/app4/update.html
{% extends "layout/base.html" %}

{% block title %}Update Friend{% endblock %}

{% block content %}
<style>
body {
background-color: #c0c0c0
}
</style>
<section>
    <form action="" method="post">{% csrf_token %}{{ form.as_p }}
        <input type="submit" value="Confirm" />
    </form>
    <a href="{% url 'index' %}"><button> decline </button></a>
</section>
{% endblock %}

app4/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block style %}
    {% endblock style %}
</head>

<body>
    <nav>
        <a href="{% url 'index' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Главная</a>
        {% for rubric in rubrics %}
        <a href="{% url 'by_rubric' rubric.pk %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">{{ rubric.name }}</a>
        {% endfor %}
    </nav>
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>